json.id user.id
json.first_name user.first_name
json.middle_name user.middle_name
json.last_name user.last_name
json.full_name user.full_name
json.email user.email
json.status user.status
json.experience user.experience
json.career_level user.career_level
json.created_at user.created_at
json.updated_at user.updated_at